package crain.client.view.pages;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import crain.client.events.CreateMemoryAdapterEvent;
import crain.client.service.SettingsService;
import crain.client.util.NullUtil;
import crain.client.view.events.SettingsPageChangeEvent;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

@Slf4j
@Component
public class SettingsPage {
    private JComboBox<String> connectionTypeSelection;
    private JTextField consoleIpField;
    private JLabel consoleIp;
    private JLabel connectionType;
    private JCheckBox enableExternalIntegration;
    private JButton saveButton;
    @Getter
    private JPanel basePanel;

    @Autowired
    private ApplicationEventPublisher applicationEventPublisher;
    @Autowired
    private SettingsService settingsService;

    public void setListeners() {
        connectionTypeSelection.setSelectedIndex(0);
        saveButton.setActionCommand("Save");
        saveButton.addActionListener(e -> {
            if ("Save".equals(e.getActionCommand())) {
                onSave();
            }
        });
        consoleIpField.setText(settingsService.getSetting(SettingsService.consoleIp));
        String savedConnectionType = settingsService.getSetting(SettingsService.connectionType);
        if (savedConnectionType != null) {
            if (savedConnectionType.equals("DOLPHIN")) {
                connectionTypeSelection.setSelectedIndex(0);
            } else {
                connectionTypeSelection.setSelectedIndex(1);
            }
        }
        String integrationEnabled = settingsService.getSetting(SettingsService.externalIntegration);
        if (integrationEnabled != null) {
            enableExternalIntegration.setSelected(Boolean.parseBoolean(integrationEnabled));
        }
    }

    private void onSave() {
        String consoleAddress = consoleIpField.getText().trim();
        Boolean externalIntegration = enableExternalIntegration.isSelected();

        log.debug("Currently Selected Item: {}", connectionTypeSelection.getSelectedItem());
        //noinspection DataFlowIssue || getPotentialNull handles the NPE
        var adapterType = Objects.equals(NullUtil.getPotentialNull(() -> connectionTypeSelection.getSelectedItem().toString().trim()), "Dolphin")
                ? CreateMemoryAdapterEvent.MemoryAdapterType.DOLPHIN
                : CreateMemoryAdapterEvent.MemoryAdapterType.NINTENDONT;
        applicationEventPublisher.publishEvent(new SettingsPageChangeEvent(adapterType, consoleAddress, externalIntegration));
    }


    private void createUIComponents() {
        connectionTypeSelection = new JComboBox<>(new String[]{"Dolphin", "Nintendont"});
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        basePanel = new JPanel();
        basePanel.setLayout(new GridLayoutManager(4, 2, new Insets(10, 5, 10, 10), -1, -1));
        basePanel.setMaximumSize(new Dimension(-1, -1));
        basePanel.setMinimumSize(new Dimension(150, 100));
        basePanel.setPreferredSize(new Dimension(336, 100));
        basePanel.add(connectionTypeSelection, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        consoleIpField = new JTextField();
        basePanel.add(consoleIpField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, -1), null, 0, false));
        consoleIp = new JLabel();
        consoleIp.setHorizontalTextPosition(4);
        consoleIp.setText("Console IP Address");
        basePanel.add(consoleIp, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(64, 16), null, 0, false));
        connectionType = new JLabel();
        connectionType.setHorizontalTextPosition(0);
        connectionType.setText("Connection Type");
        basePanel.add(connectionType, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(64, 16), null, 0, false));
        enableExternalIntegration = new JCheckBox();
        enableExternalIntegration.setHorizontalTextPosition(2);
        enableExternalIntegration.setText("Enable Coop Tracker Updates");
        basePanel.add(enableExternalIntegration, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setText("Save");
        basePanel.add(saveButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return basePanel;
    }

}
