# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml -pl Model
        mvn -B package --file pom.xml -pl Server,Client

    - name: Upload Client
      uses: actions/upload-artifact@v3
      with:
        name: WWR-Client.jar
        path: ./Client/target/*.jar
        
    - name: Upload Server
      uses: actions/upload-artifact@v3
      with:
        name: WWR-Server.jar
        path: ./Server/target/*.jar
        
